### PR TITLE
change allowed origins to appropriate regex

### PR DESCRIPTION
**Pull request by lucasMontenegro**

### CODE REVIEW

**Comment by RandellDawson** [comment]
@nhcarrigan Can this be closed?

**Comment by naomi-lgbt** [comment]
@RandellDawson I believe so - it looks like this boilerplate was removed from the curriculum? https://github.com/freeCodeCamp/freeCodeCamp/commit/e3cfe80f88bb098f616c338b6b7a7b05ab676590

I doublechecked in the codebase too and could not find any references to this boilerplate...

**Review by naomi-lgbt — COMMENTED** [review]
This PR could be merged, I think - provided that we are no longer using the other domains to run tests from `/learn`... 

I see no need to maintain `localhost` in the list as that's for testing from a local dev instance of the learn platform right?

**Comment by RandellDawson** [comment]
> I see no need to maintain localhost in the list as that's for testing from a local dev instance of the learn platform right?

Technically, the user could have used `localhost` when working on these challenges locally.  There was no requirement that a public facing site had to be submitted for the challenges.

**Comment by naomi-lgbt** [comment]
I might be misunderstanding the code here, but...

The allowed origin list determines where a request can come from right? And requests to `fcctesting.js` should be related to the client-side `/learn` tests, which should currently come strictly from `freecodecamp.org` - a request from `localhost` would mean I was running a dev instance of the curriculum platform and submitting my project to that instance instead, yeah?

**Comment by naomi-lgbt** [comment]
Hey there @lucasMontenegro~!

This is a standard message notifying you that we have reviewed your pull request and decided not to merge it. Thank you for your interest in contributing, and we look forward to future contributions!

**Reason:** Restricting the allowed origins solely to the `freecodecamp.org` host will cause errors when testing changes on a local development instance (where the request origin is `localhost`). Additionally, this boilerplate is currently not used in our curriculum.

**Pull request closed without merging**
